/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.LowerCentralSeries
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Frattini

/-!
# The first step of the lower `p`-central series and the pro-`p` Frattini subgroup

For a prime `p` and a topological group `G`, the first term `P₁` of the lower `p`-central series
is the closure of the subgroup generated by the `p`-th powers of `G` together with the
commutators `⁅G, G⁆`. This file records that `P₁` is contained in the pro-`p` Frattini subgroup
`Φ`. The containment gives a quotient map `G ⧸ P₁ → G ⧸ Φ`, so a family generating `G` modulo
`P₁` generates `G` modulo `Φ` as well.

The comparison needs only that `p` is prime; the closedness of `TauCeti.proPFrattini` required
to pass to the topological closure defining `P₁` is supplied by the instance
`TauCeti.isClosed_proPFrattini`.

## Main results

* `TauCeti.pLowerCentralSeries_one_le_proPFrattini`: for `p` prime, the first term of the lower
  `p`-central series is contained in `TauCeti.proPFrattini p G`.
-/

public section

namespace TauCeti

open scoped commutatorElement

variable {p : ℕ} {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- For `p` prime, the first term of the lower `p`-central series is contained in the pro-`p`
Frattini subgroup: `pLowerCentralSeries p G 1 ≤ proPFrattini p G`. The only hypothesis is that
`p` is prime; no compactness or finite generation of `G` is required. -/
theorem pLowerCentralSeries_one_le_proPFrattini (hp : p.Prime) :
    pLowerCentralSeries p G 1 ≤ proPFrattini p G := by
  rw [pLowerCentralSeries_succ, pLowerCentralSeries_zero]
  refine (pLowerCentralStep_le_iff isClosed_proPFrattini).mpr
    ⟨fun x _ ↦ pow_mem_proPFrattini x, ?_⟩
  refine Subgroup.commutator_le.mpr fun h _ g _ ↦ ?_
  exact commutator_le_proPFrattini hp (Subgroup.commutator_mem_commutator
    (Subgroup.mem_top h) (Subgroup.mem_top g))

end TauCeti
