/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.LowerCentralSeries
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Frattini

/-!
# The first step of the lower `p`-central series and the pro-`p` Frattini subgroup

For a prime `p` and a topological group `G`, both the first term `P₁` of the lower `p`-central
series and the pro-`p` Frattini subgroup are generated by the `p`-th powers together with the
commutators. This file records the resulting comparison `P₁ ≤ Φ`, which is the bridge between
the two descriptions: statements proved about the Frattini quotient `G ⧸ Φ` transfer to the
first graded piece of the lower `p`-central series, and a generator of `G` modulo `Φ` is in
particular a generator modulo `P₁`.

The comparison needs only that `p` is prime; the closedness of `TauCeti.proPFrattini` required
to pass to the topological closure defining `P₁` is supplied by the instance
`TauCeti.isClosed_proPFrattini`.

## Main results

* `TauCeti.pLowerCentralSeries_one_le_proPFrattini`: for `p` prime, the first term of the lower
  `p`-central series is contained in `TauCeti.proPFrattini p G`.
-/

public section

namespace TauCeti

open scoped commutatorElement

variable {p : ℕ} {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- For `p` prime, the first term of the lower `p`-central series is contained in the pro-`p`
Frattini subgroup. Both generating families of `pLowerCentralSeries p G 1` — the `p`-th powers
and the commutators `⁅G, G⁆` — lie in `proPFrattini p G`, which is closed, so the topological
closure defining the former is contained in it as well. -/
theorem pLowerCentralSeries_one_le_proPFrattini (hp : p.Prime) :
    pLowerCentralSeries p G 1 ≤ proPFrattini p G := by
  rw [pLowerCentralSeries_succ, pLowerCentralSeries_zero]
  refine (pLowerCentralStep_le_iff isClosed_proPFrattini).mpr
    ⟨fun x _ ↦ pow_mem_proPFrattini x, ?_⟩
  refine Subgroup.commutator_le.mpr fun h _ g _ ↦ ?_
  exact commutator_le_proPFrattini hp (Subgroup.commutator_mem_commutator
    (Subgroup.mem_top h) (Subgroup.mem_top g))

end TauCeti
