/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Commutator.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Frattini

/-!
# The lower `p`-central series of a topological group

The **lower `p`-central series** of a topological group `G` is the descending chain of subgroups
obtained by iterating the pro-`p` Frattini construction. Writing `Φ` for the operation sending a
subgroup `H` to the subgroup generated by the `p`-th powers of `H` and the commutators `[G, H]`,
the series is `P₀ = G`, `Pₙ₊₁ = Φ Pₙ`.

This is the `p`-analogue of `Subgroup.lowerCentralSeries`: where the ordinary lower central
series repeatedly takes commutators with the whole group, the lower `p`-central series also
throws in `p`-th powers at each stage. It is the filtration relative to which the associated
graded object of a pro-`p` group is a Lie algebra over `𝔽ₚ`, and it is the standard tool for
studying pro-`p` groups by successive elementary abelian quotients.

## Main definitions

* `TauCeti.pLowerCentralStep p G H`: one step of the series, the subgroup generated by the
  `p`-th powers of `H` together with the commutators `⁅g, h⁆` for `g : G` and `h : H`.
* `TauCeti.pLowerCentralSeries p G n`: the `n`-th term of the lower `p`-central series.

## Main results

* `TauCeti.pLowerCentralSeries_succ`: the defining recursion.
* `TauCeti.pLowerCentralSeries_antitone`: the series is descending.
* `TauCeti.pow_mem_pLowerCentralStep` and `TauCeti.commutator_mem_pLowerCentralStep`: the two
  generating families lie in the next term.
* `TauCeti.pLowerCentralStep_le_proPFrattini`: the first step is contained in the pro-`p`
  Frattini subgroup, tying this filtration to `TauCeti.proPFrattini`.

## Implementation notes

`pLowerCentralStep` takes the **topological** closure of the subgroup generated by the `p`-th
powers of `H` and the commutators `⁅H, ⊤⁆`. The topological closure is essential rather than
cosmetic: in a profinite group the abstract `Subgroup.closure` of those generators need not be
closed, so without it the terms of the series would not be closed subgroups and the associated
graded object would not be the intended one. Compare `TauCeti.proPFrattini`, which is an
intersection of open normal subgroups and so is closed by construction.

The definition is stated for an arbitrary topological group, with no compactness hypothesis; the
comparison with the intersection description of `TauCeti.proPFrattini` is stated separately.
-/

public section

namespace TauCeti

open scoped commutatorElement

section Defs

variable (p : ℕ) (G : Type*) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- One step of the lower `p`-central series: the topological closure of the subgroup generated
by the `p`-th powers of `H` together with the commutators `⁅H, ⊤⁆`. -/
@[expose]
def pLowerCentralStep (H : Subgroup G) : Subgroup G :=
  (Subgroup.closure ((· ^ p) '' (H : Set G)) ⊔ ⁅H, (⊤ : Subgroup G)⁆).topologicalClosure

/-- The lower `p`-central series of `G`: `P₀ = G` and `Pₙ₊₁` is one `pLowerCentralStep` of `Pₙ`.
This is the `p`-analogue of `Subgroup.lowerCentralSeries`, additionally closing up under `p`-th
powers at every stage. -/
@[expose]
def pLowerCentralSeries : ℕ → Subgroup G
  | 0 => ⊤
  | n + 1 => pLowerCentralStep p G (pLowerCentralSeries n)

end Defs

variable {p : ℕ} {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

@[simp]
theorem pLowerCentralSeries_zero : pLowerCentralSeries p G 0 = ⊤ := rfl

/-- The defining recursion of the lower `p`-central series. -/
theorem pLowerCentralSeries_succ (n : ℕ) :
    pLowerCentralSeries p G (n + 1) = pLowerCentralStep p G (pLowerCentralSeries p G n) := rfl

/-- The underlying algebraic subgroup of a step, before taking the topological closure. -/
theorem pLowerCentralStep_base_le {H : Subgroup G} :
    Subgroup.closure ((· ^ p) '' (H : Set G)) ⊔ ⁅H, (⊤ : Subgroup G)⁆ ≤ pLowerCentralStep p G H :=
  Subgroup.le_topologicalClosure _

/-- Every `p`-th power of an element of `H` lies in the next term. -/
theorem pow_mem_pLowerCentralStep {H : Subgroup G} {h : G} (hh : h ∈ H) :
    h ^ p ∈ pLowerCentralStep p G H :=
  pLowerCentralStep_base_le <| Subgroup.mem_sup_left <|
    Subgroup.subset_closure ⟨h, hh, rfl⟩

/-- Every commutator `⁅h, g⁆` with `h ∈ H` lies in the next term. -/
theorem commutator_mem_pLowerCentralStep {H : Subgroup G} {h : G} (hh : h ∈ H) (g : G) :
    ⁅h, g⁆ ∈ pLowerCentralStep p G H :=
  pLowerCentralStep_base_le <| Subgroup.mem_sup_right <|
    Subgroup.commutator_mem_commutator hh (Subgroup.mem_top g)

/-- `pLowerCentralStep` is monotone in its subgroup argument. -/
theorem pLowerCentralStep_mono {H K : Subgroup G} (h : H ≤ K) :
    pLowerCentralStep p G H ≤ pLowerCentralStep p G K :=
  Subgroup.topologicalClosure_mono <| sup_le_sup
    (Subgroup.closure_mono (Set.image_mono h))
    (Subgroup.commutator_mono h le_rfl)

/-- A step of the lower `p`-central series lands inside the subgroup it started from, provided
that subgroup is normal and closed: `p`-th powers of `H` stay in `H`, and
`⁅h, g⁆ = (h * g * h⁻¹) * g⁻¹` stays in `H` because `h * g * h⁻¹ * g⁻¹` is a product of `h` with
the `H`-conjugate `g * h⁻¹ * g⁻¹`. -/
theorem pLowerCentralStep_le {H : Subgroup G} [H.Normal] (hH : IsClosed (H : Set G)) :
    pLowerCentralStep p G H ≤ H := by
  refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_) hH
  · refine Subgroup.closure_le _ |>.mpr ?_
    rintro x ⟨h, hh, rfl⟩
    exact H.pow_mem hh p
  · refine Subgroup.commutator_le.mpr fun h hh g _ => ?_
    have : ⁅h, g⁆ = h * (g * h⁻¹ * g⁻¹) := by
      rw [commutatorElement_def]; group
    rw [this]
    exact H.mul_mem hh (‹H.Normal›.conj_mem h⁻¹ (H.inv_mem hh) g)

/-- One step of the series is normal as soon as the subgroup it starts from is: conjugating a
`p`-th power or a commutator produces another generator of the same kind. -/
instance pLowerCentralStep_normal (H : Subgroup G) [H.Normal] :
    (pLowerCentralStep p G H).Normal :=
  have powNormal : (Subgroup.closure ((· ^ p) '' (H : Set G))).Normal := by
    constructor
    intro n hn c
    induction hn using Subgroup.closure_induction with
    | mem x hx =>
      obtain ⟨h, hh, rfl⟩ := hx
      refine Subgroup.subset_closure ⟨c * h * c⁻¹, ‹H.Normal›.conj_mem h hh c, ?_⟩
      simp [conj_pow]
    | one => simp
    | mul x y _ _ hx hy =>
      have : c * (x * y) * c⁻¹ = c * x * c⁻¹ * (c * y * c⁻¹) := by group
      rw [this]
      exact Subgroup.mul_mem _ hx hy
    | inv x _ hx =>
      have : c * x⁻¹ * c⁻¹ = (c * x * c⁻¹)⁻¹ := by group
      rw [this]
      exact Subgroup.inv_mem _ hx
  Subgroup.is_normal_topologicalClosure _

/-- Every term of the lower `p`-central series is normal. -/
instance pLowerCentralSeries_normal (n : ℕ) : (pLowerCentralSeries p G n).Normal := by
  induction n with
  | zero => rw [pLowerCentralSeries_zero]; infer_instance
  | succ n ih => rw [pLowerCentralSeries_succ]; exact pLowerCentralStep_normal _

/-- **`p`-th powers raise the degree.** If `x` lies in `P k`, then `x ^ p` lies in `P (k + 1)`.
This is the membership statement that makes the `p`-power operator on the associated graded
object well defined. -/
theorem pow_mem_pLowerCentralSeries (k : ℕ) {x : G} (hx : x ∈ pLowerCentralSeries p G k) :
    x ^ p ∈ pLowerCentralSeries p G (k + 1) := by
  rw [pLowerCentralSeries_succ]
  exact pow_mem_pLowerCentralStep hx

/-- **Commutators raise the degree by one.** If `x ∈ P k` then `⁅x, y⁆ ∈ P (k + 1)` for *any*
`y : G`, because each step adjoins the commutators `⁅P k, ⊤⁆`. This is the degree-shift in the
form the graded bracket needs; the sharper `⁅P j, P k⁆ ≤ P (j + k + 1)` refines it. -/
theorem commutator_mem_pLowerCentralSeries_succ (k : ℕ) {x : G}
    (hx : x ∈ pLowerCentralSeries p G k) (y : G) :
    ⁅x, y⁆ ∈ pLowerCentralSeries p G (k + 1) := by
  rw [pLowerCentralSeries_succ]
  exact commutator_mem_pLowerCentralStep hx y

/-- The lower `p`-central series is descending, given that each term is closed. -/
theorem pLowerCentralSeries_succ_le (n : ℕ)
    (hn : IsClosed ((pLowerCentralSeries p G n : Subgroup G) : Set G)) :
    pLowerCentralSeries p G (n + 1) ≤ pLowerCentralSeries p G n := by
  rw [pLowerCentralSeries_succ]
  exact pLowerCentralStep_le (p := p) (G := G) hn

/-- Every term of the lower `p`-central series past the first is closed: it is a topological
closure by construction. -/
theorem isClosed_pLowerCentralSeries_succ (n : ℕ) :
    IsClosed ((pLowerCentralSeries p G (n + 1) : Subgroup G) : Set G) := by
  rw [pLowerCentralSeries_succ]
  exact Subgroup.isClosed_topologicalClosure _

/-- The first step of the lower `p`-central series is contained in the pro-`p` Frattini subgroup:
its two generating families are exactly the `p`-th powers and the commutators, both of which lie
in `proPFrattini p G`. -/
theorem pLowerCentralStep_le_proPFrattini (hp : p.Prime)
    (hF : IsClosed ((proPFrattini p G : Subgroup G) : Set G)) :
    pLowerCentralSeries p G 1 ≤ proPFrattini p G := by
  rw [pLowerCentralSeries_succ, pLowerCentralSeries_zero]
  refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_) hF
  · refine Subgroup.closure_le _ |>.mpr ?_
    rintro x ⟨h, -, rfl⟩
    exact pow_mem_proPFrattini h
  · refine Subgroup.commutator_le.mpr fun h _ g _ => ?_
    exact commutator_le_proPFrattini hp (Subgroup.commutator_mem_commutator
      (Subgroup.mem_top h) (Subgroup.mem_top g))

end TauCeti
